### PR TITLE
Update bootstrap file to use latest pip version.

### PR DESCRIPTION
**Pull request by chadac**
*Issue #, if available:* N/A

*Description of changes:* Added line to `bootstrap.sh` to upgrade `pip` version to latest on Docker build. This resolves an issue where we could not install raw packages using the `pyproject.toml` format.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by cjames23 — APPROVED** [review]
This will ensure on start up that the containers are always using the most up to date pip.

**Comment by subashcanapathy** [comment]
This is a good change, and we did make this one recently on the MWAA 2.0 release. Accepting merge for main branch, will need to cherry pick this to the other branches subsequently.

**Review by subashcanapathy — APPROVED** [review]
approving for main branch merge

**Comment by subashcanapathy** [comment]
@o-nikolas , @dhegberg - review and approve when you get time.

**Review by o-nikolas — APPROVED** [review]

**Pull request merged**
