### PR TITLE
M1 mac

### PR DESCRIPTION
**Pull request by janrito**
*Issue #, if available:*
https://github.com/aws/aws-mwaa-local-runner/issues/131
https://github.com/aws/aws-mwaa-local-runner/issues/136

*Description of changes:

modifies scripts and compose files to docker on amd64 emulation  mode

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by reddy-s** [comment]
Any timelines on when this will be merged?

**Comment by janrito** [comment]
@subashcanapathy any thoughts on this, - can we help in any way?

**Comment by jgc93** [comment]
@janrito  @reddy-s what python version are you installing onto M1? from homebrew? 
i've tried installing 3.8-3.10 (3.7 not installable on M1) and keep erroring out on `mwaa-local-env start`.

**Comment by janrito** [comment]
@jgc93 what is the error you are getting? 

I think this uses the default python on amazon linux, which is 3.9? https://docs.aws.amazon.com/linux/al2022/release-notes/all-packages-al2022-20220824.html

**Comment by john-jac** [comment]
Fixed with https://github.com/aws/aws-mwaa-local-runner/pull/169

**Comment by janrito** [comment]
great

**Pull request closed without merging**
