### PR TITLE
v2.8.1 Update MariaDB RPM links

### PR DESCRIPTION
**Pull request by sshirsat-js**
*Issue #, if available:*

*Description of changes:*
Update MariaDB RPM links

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by jplock** [comment]
@michaelfu1029 is this something that we can review and merge? It's impacting one of my accounts I support.

**Comment by jluengo1983** [comment]
I was having a hard time with my Macbook M3 getting the mariaDB error messages (below) , and I just saw this commit with the new MariaDB links and boom, I was able to build the docker image, THANKS!

51.47 ++ uname -p
51.47 + wget https://archive.mariadb.org/yum/10.8.6/rhel7-aarch64/rpms/MariaDB-common-10.8.6-1.el7.centos.aarch64.rpm -P /mariadb_rpm
51.47 --2024-11-22 19:15:49--  https://archive.mariadb.org/yum/10.8.6/rhel7-aarch64/rpms/MariaDB-common-10.8.6-1.el7.centos.aarch64.rpm
51.50 Resolving archive.mariadb.org (archive.mariadb.org)... 138.201.152.105, 2a01:4f8:c17:cad6::1
51.78 Connecting to archive.mariadb.org (archive.mariadb.org)|138.201.152.105|:443... connected.
52.23 HTTP request sent, awaiting response... 404 Not Found
52.41 2024-11-22 19:15:50 ERROR 404: Not Found.

**Comment by hafizmujadidKhalid** [comment]
@sshirsat-js ! can we replicate this fix for other releases as well?

**Comment by sshirsat-js** [comment]
Sure, you can On Nov 22, 2024, at 13:26, Hafiz Khalid ***@***.***> wrote:﻿
@sshirsat-js ! can we replicate this fix for other releases as well?

**Comment by devin-hc** [comment]
> @michaelfu1029 is this something that we can review and merge? It's impacting one of my accounts I support.

Our CICD is broken as well, for our MWAA production setup.

A review / merge would be awesome.

**Comment by michaelfu1029** [comment]
Tested this locally and it seems to work. I will apply this change for the other versions too

**Review by mayushko26 — APPROVED** [review]

**Review by michaelfu1029 — APPROVED** [review]

**Pull request merged**
